// Precompile JSON Schema 2020-12 в standalone-валидатор. Это нужно потому, что
// в MV3 service worker запрещён `unsafe-eval` (см. CSP), а Ajv по умолчанию
// генерирует валидатор через `new Function(code)`. Standalone-режим Ajv создаёт
// готовый JS-модуль, который можно импортировать без runtime eval.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import Ajv from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const OUT_DIR = resolve(ROOT, "src/analysis/__generated__");

// Список схем для прекомпиляции. Каждая схема компилируется в отдельный
// standalone-модуль рядом с другими валидаторами.
const SCHEMAS = [
  {
    schemaPath: resolve(ROOT, "schemas/analysis-response.schema.json"),
    outJs: resolve(OUT_DIR, "validate-analysis.js"),
    outDts: resolve(OUT_DIR, "validate-analysis.d.ts"),
  },
  {
    schemaPath: resolve(ROOT, "schemas/reconcile-response.schema.json"),
    outJs: resolve(OUT_DIR, "validate-reconcile.js"),
    outDts: resolve(OUT_DIR, "validate-reconcile.d.ts"),
  },
];

// Ajv standalone хардкодит require("ajv/dist/runtime/ucs2length").default даже
// в esm-режиме. В MV3 service worker (тип "module") нет CommonJS — require кидает
// ReferenceError на этапе загрузки и регистрация SW падает со Status code 15.
// Заменяем require на инлайн-функцию.
const UCS2LENGTH_INLINE = `(function ucs2length(str){const len=str.length;let length=0;let pos=0;let value;while(pos<len){length++;value=str.charCodeAt(pos++);if(value>=0xd800&&value<=0xdbff&&pos<len){value=str.charCodeAt(pos);if((value&0xfc00)===0xdc00)pos++;}}return length;})`;

const DTS_TEMPLATE = `// Auto-generated by scripts/precompile-schema.mjs. Do not edit.
import type { ErrorObject } from "ajv";
declare const validate: ((data: unknown) => boolean) & {
  errors?: ErrorObject[] | null;
};
export default validate;
`;

mkdirSync(OUT_DIR, { recursive: true });

for (const { schemaPath, outJs, outDts } of SCHEMAS) {
  const schema = JSON.parse(readFileSync(schemaPath, "utf8"));

  const ajv = new Ajv.default({
    allErrors: true,
    strict: false,
    allowUnionTypes: true,
    code: { source: true, esm: true },
  });
  const validate = ajv.compile(schema);
  const moduleCode = standaloneCode.default(ajv, validate);

  const patched = moduleCode.replace(
    /require\("ajv\/dist\/runtime\/ucs2length"\)\.default/g,
    UCS2LENGTH_INLINE,
  );
  if (/require\(/.test(patched)) {
    throw new Error(
      `[precompile-schema] generated module for ${schemaPath} still contains require(); add another inline helper`,
    );
  }

  writeFileSync(outJs, patched, "utf8");
  writeFileSync(outDts, DTS_TEMPLATE, "utf8");
  console.log(`[precompile-schema] wrote ${outJs}`);
}
